var topojson=require('C:/Users/28737/Desktop/新建文件夹/vendor/topojson.min.js');
var w=require('C:/Users/28737/Desktop/新建文件夹/countries-110m.json');
var countries=topojson.feature(w,w.objects.countries);
var names=countries.features.map(f=>f.properties.name);
console.log('countries:',countries.features.length);
console.log('China in:',names.indexOf('China'),'Taiwan in:',names.indexOf('Taiwan'));
var china=countries.features.find(f=>f.properties.name==='China');
console.log('china type:',china.geometry.type,'polys:',china.geometry.coordinates.length);
var mesh=topojson.mesh(w,w.objects.countries,function(a,b){return a!==b;});
console.log('borders mesh:',mesh.type, mesh.coordinates.length);
var land=topojson.feature(w,w.objects.land);
console.log('land:',land.features[0].geometry.type,'polys:',land.features[0].geometry.coordinates.length);
var totalPts=0; land.features[0].geometry.coordinates.forEach(p=>p.forEach(r=>totalPts+=r.length)); console.log('land total pts:',totalPts);
