/* 威胁组织数据库合并脚本 v1.0
 * 功能：读取现有 threats.js + new_orgs.jsonl，追加新增组织，生成 threats.js v3.0
 * 约束：仅基于公开可验证事实，不编造叙事内容
 */
const fs = require('fs');
const path = require('path');

const ROOT = __dirname;
const SRC = path.join(ROOT, 'threats.js');
const OUT = path.join(ROOT, 'threats.js');
const NEWL = path.join(ROOT, 'new_orgs.jsonl');

// 读取并解析现有 threats.js 中的 THREAT_DATA.organizations
const content = fs.readFileSync(SRC, 'utf8');
const match = content.match(/const\s+THREAT_DATA\s*=\s*\{organizations:\s*(\[[\s\S]*?\])\s*\}\s*;/);
if (!match) {
  console.error('无法解析 threats.js 中的 THREAT_DATA.organizations');
  process.exit(1);
}
const existing = eval(match[1]);

// 读取 new_orgs.jsonl
let fromTemp = [];
if (fs.existsSync(NEWL)) {
  const lines = fs.readFileSync(NEWL, 'utf8').split('\n').map(l => l.trim()).filter(Boolean);
  for (const line of lines) {
    if (line === '<!--END-->') continue;
    try { fromTemp.push(JSON.parse(line)); } catch (e) { console.warn('解析 JSONL 行失败:', line.slice(0, 80)); }
  }
}

// 新增组织：覆盖中国海外利益重点国别，基于公开事实字段
const additional = [
  // 直接针对中国海外利益的重点组织
  { id: 'bla', name: '俾路支解放军', aliases: ['BLA', 'Balochistan Liberation Army', '俾路支解放武装'], type: '恐怖组织', category: '民族分离', subcategory: '俾路支民族主义武装', founded: '2000', foundedLocation: '巴基斯坦俾路支省', status: '活跃', threatLevel: 8.5, threatTrend: '上升', leader: '巴希尔·泽布（公开信息有限）', formerLeaders: ['阿斯拉姆·俾路支（2019/2020死亡）'], members: '约数百至数千人', operatingRegions: ['巴基斯坦', '阿富汗', '伊朗'], ideology: '俾路支民族独立，反对外来投资与中央政府资源控制', funding: '跨境走私、外部捐助、绑架赎金', fundingEstimate: '据公开报道难以估算', designation: ['美国指定外国恐怖组织（2019）', '巴基斯坦政府列禁', '英国指定恐怖组织', '欧盟指定恐怖组织'], weaponLevel: '轻武器+IED+自杀式袭击', cyberCapability: '低——主要通过社交媒体发布声明', description: '俾路支解放军（BLA）是巴基斯坦俾路支省主要分离主义武装组织之一，2000年前后从俾路支学生组织中分化而来。该组织以俾路支独立为目标，频繁袭击巴基斯坦安全部队、政府设施及被视为代表外来经济利益的目标。2018年以来，该组织多次将矛头指向中巴经济走廊（CPEC）项目和中国公民。2019年美国国务院将其列入外国恐怖组织名单，其下属“马吉德旅”以自杀式袭击著称。', structure: [{role: '最高指挥官', current: '巴希尔·泽布', desc: '组织战略决策'}, {role: '马吉德旅', current: '—', desc: '自杀式袭击分支'}, {role: '军事委员会', current: '—', desc: '行动策划'}, {role: '情报与安全部门', current: '—', desc: '目标侦察与内部安全'}, {role: '宣传部门', current: '—', desc: '媒体声明与网络信息发布'}], events: [{date: '2018-11-23', title: '卡拉奇中国领事馆遇袭', desc: 'BLA袭击中国驻卡拉奇总领事馆', casualties: '4人死亡（含2名警察）', impact: '高'}, {date: '2019-05-11', title: '瓜达尔珍珠洲际酒店袭击', desc: 'BLA武装分子袭击瓜达尔港附近酒店，酒店内有中国及其他外国投资者', casualties: '至少5人死亡（含4名袭击者）', impact: '高'}, {date: '2022-04-26', title: '卡拉奇大学孔子学院班车爆炸', desc: 'BLA马吉德旅女性自杀式袭击者袭击孔子学院班车', casualties: '4人死亡，包括3名中国公民', impact: '极高'}, {date: '2024-10-06', title: '卡拉奇国际机场附近中资企业车队遇袭', desc: 'BLA对卡拉奇真纳国际机场附近中资企业车队发动自杀式袭击', casualties: '2名中国公民死亡，多人受伤', impact: '极高'}], statements: [{date: '2022-04', source: 'BLA声明', content: '宣称对卡拉奇大学孔子学院班车袭击负责，称目标是“中国项目及其人员”。'}, {date: '2024-10', source: 'BLA声明', content: '宣称对卡拉奇机场附近中资企业车队袭击负责，再次警告外国投资者。'}] },
  { id: 'ttp', name: '巴基斯坦塔利班', aliases: ['TTP', 'Tehrik-e Taliban Pakistan', '巴基斯坦塔利班运动'], type: '恐怖组织', category: '宗教极端', subcategory: '逊尼派萨拉菲圣战', founded: '2007', foundedLocation: '巴基斯坦联邦直辖部落地区', status: '活跃', threatLevel: 8.5, threatTrend: '上升', leader: '努尔·瓦利·马哈苏德', formerLeaders: ['贝图拉·马哈苏德（2009击毙）', '哈基穆拉·马哈苏德（2013击毙）', '法兹卢拉（2018击毙）'], members: '约3,000-6,000人', operatingRegions: ['巴基斯坦', '阿富汗'], ideology: '推翻巴基斯坦政府，建立伊斯兰教法国家，袭击北约及巴安全部队', funding: '绑架赎金、抢劫、外部捐助、毒品贸易', fundingEstimate: '年收入数千万美元', designation: ['联合国安理会1267委员会制裁', '美国指定外国恐怖组织', '巴基斯坦列禁'], weaponLevel: '轻武器+IED+自杀式炸弹', cyberCapability: '中——利用社交媒体宣传', description: '巴基斯坦塔利班（TTP）是巴基斯坦最主要的圣战武装组织之一，2007年由多个部落武装合并成立。该组织在巴基斯坦西北部频繁发动针对安全部队、学校、平民和外国目标的袭击，并与阿富汗塔利班保持复杂关系。TTP活动范围覆盖中巴经济走廊北线经过的开伯尔-普什图省，对中方人员和项目构成现实威胁。', structure: [{role: '埃米尔', current: '努尔·瓦利·马哈苏德', desc: '最高领导人'}, {role: '军事委员会', current: '—', desc: '袭击策划'}, {role: '舒拉委员会', current: '—', desc: '决策咨询'}, {role: '宣传部门', current: '—', desc: '媒体与网络信息发布'}], events: [{date: '2007-12', title: 'TTP成立', desc: '多个部落武装合并成立巴基斯坦塔利班', casualties: '—', impact: '高'}, {date: '2014-12-16', title: '白沙瓦学校屠杀', desc: 'TTP袭击白沙瓦军人子弟学校', casualties: '149人死亡，含132名学生', impact: '极端'}, {date: '2021-08', title: '阿富汗塔利班胜利后攻势', desc: 'TTP趁阿富汗局势变化加大在巴袭击频率', casualties: '数百人伤亡', impact: '高'}, {date: '2023-01', title: '白沙瓦清真寺爆炸', desc: 'TTP在白沙瓦警察局附近清真寺发动自杀式爆炸', casualties: '100+人死亡', impact: '极高'}], statements: [{date: '2021-08', source: 'TTP声明', content: '在阿富汗塔利班胜利后呼吁巴基斯坦政府接受其政治条件。'}] },
  { id: 'etim', name: '东突厥斯坦伊斯兰运动', aliases: ['ETIM', 'TIP', '突厥斯坦伊斯兰党', '东伊运'], type: '恐怖组织', category: '宗教极端', subcategory: '分裂主义圣战', founded: '1993', foundedLocation: '中国新疆/巴基斯坦瓦济里斯坦', status: '潜伏活跃', threatLevel: 8.0, threatTrend: '稳定', leader: '不详', formerLeaders: ['艾山·买合苏木（2003击毙）', '阿卜杜勒·哈克（2010击毙）'], members: '约200-300名骨干', operatingRegions: ['中国新疆', '阿富汗', '巴基斯坦', '叙利亚', '土耳其', '中亚'], ideology: '以暴力分裂中国新疆，建立所谓“东突厥斯坦”', funding: '境外捐助、犯罪活动、毒品与武器走私', fundingEstimate: '规模较小', designation: ['联合国安理会1267委员会制裁', '美国指定外国恐怖组织', '中国公安部认定恐怖组织', '欧盟指定恐怖组织'], weaponLevel: '轻武器+IED', cyberCapability: '低', description: '东突厥斯坦伊斯兰运动（ETIM）是被联合国、中国、美国等多国认定的恐怖组织。该组织以暴力分裂中国新疆为目标，曾在境外策划和实施针对中国驻外机构及人员的袭击图谋。其核心成员长期流窜于阿富汗-巴基斯坦边境及叙利亚等地，被中国视为“东突”恐怖势力的主要代表。', structure: [{role: '领导人', current: '不详', desc: '分散领导'}, {role: '军事委员会', current: '—', desc: '袭击策划'}, {role: '宣传部门', current: '—', desc: '网络视频与音频宣传'}, {role: '海外网络', current: '—', desc: '中亚、中东活动'}], events: [{date: '2008', title: '北京奥运会威胁', desc: '威胁对北京奥运会发动袭击，将新疆问题国际化', casualties: '未遂', impact: '高'}, {date: '2011', title: '艾山·买合苏木之子被击毙', desc: '在巴基斯坦瓦济里斯坦地区遭美军无人机空袭死亡', casualties: '—', impact: '高'}, {date: '2013-2017', title: '叙利亚参战', desc: '部分成员潜入叙利亚参与内战', casualties: '—', impact: '高'}], statements: [{date: '2008', source: 'TIP视频声明', content: '威胁对北京奥运会发动袭击，将新疆问题国际化。'}] },

  // 南亚
  { id: 'let', name: '虔诚军', aliases: ['Lashkar-e-Taiba', 'LeT', '正义军'], type: '恐怖组织', category: '宗教极端', subcategory: '克什米尔圣战武装', founded: '1990', foundedLocation: '巴基斯坦旁遮普省', status: '活跃', threatLevel: 8.5, threatTrend: '稳定', leader: '哈菲兹·赛义德（被联合国制裁）', formerLeaders: [], members: '数千人', operatingRegions: ['巴基斯坦', '印度', '阿富汗'], ideology: '在克什米尔及印度建立伊斯兰统治，对印度发动圣战', funding: '公开慈善机构、海外捐助、犯罪活动', fundingEstimate: '年收入数千万美元', designation: ['联合国安理会1267委员会制裁', '美国指定外国恐怖组织', '印度指定恐怖组织', '巴基斯坦部分时期列禁'], weaponLevel: '轻武器+IED+自杀式袭击', cyberCapability: '中——利用社交媒体与网站宣传', description: '虔诚军是巴基斯坦境内规模较大的克什米尔圣战武装组织，被联合国、美国、印度等多国列为恐怖组织。该组织被指控多次发动针对印度目标的重大袭击，包括2008年孟买连环恐怖袭击。', structure: [{role: '埃米尔', current: '哈菲兹·赛义德', desc: '创始人与精神领袖'}, {role: '军事委员会', current: '—', desc: '行动指挥'}, {role: '慈善掩护网络', current: '—', desc: '资金筹集与人员招募'}], events: [{date: '2001-12-13', title: '印度议会袭击', desc: '袭击印度议会大楼，引发印巴军事对峙', casualties: '9人死亡', impact: '极高'}, {date: '2008-11-26', title: '孟买连环恐袭', desc: 'LeT武装分子袭击孟买多个目标', casualties: '166人死亡', impact: '极端'}, {date: '2019-02-14', title: '普尔瓦马袭击', desc: '自杀式汽车炸弹袭击印度准军事车队', casualties: '40人死亡', impact: '高'}], statements: [{date: '2008-12', source: 'LeT发言人', content: '否认参与孟买袭击，但要求国际社会关注克什米尔问题。'}] },
  { id: 'jem', name: '穆罕默德军', aliases: ['Jaish-e-Mohammed', 'JeM', '穆罕默德战士'], type: '恐怖组织', category: '宗教极端', subcategory: '克什米尔圣战武装', founded: '2000', foundedLocation: '巴基斯坦俾路支省', status: '活跃', threatLevel: 8.5, threatTrend: '稳定', leader: '马苏德·阿查尔（联合国制裁）', formerLeaders: [], members: '数百至数千人', operatingRegions: ['巴基斯坦', '印度', '阿富汗'], ideology: '将克什米尔从印度分离并建立伊斯兰政权', funding: '海外捐助、犯罪活动、绑架赎金', fundingEstimate: '规模中等', designation: ['联合国安理会1267委员会制裁', '美国指定外国恐怖组织', '印度指定恐怖组织', '巴基斯坦部分时期列禁', '欧盟指定恐怖组织'], weaponLevel: '轻武器+IED+自杀式炸弹', cyberCapability: '低——主要通过社交媒体发布声明', description: '穆罕默德军是2000年在巴基斯坦成立的克什米尔圣战武装，以发动高调袭击著称，包括2001年印度议会袭击和2019年普尔瓦马自杀式炸弹袭击。', structure: [{role: '埃米尔', current: '马苏德·阿查尔', desc: '最高领袖'}, {role: '军事指挥官', current: '—', desc: '袭击策划'}, {role: '招募网络', current: '—', desc: '南亚地区招募'}], events: [{date: '2001-12-13', title: '印度议会袭击', desc: '袭击印度议会，引发印巴军事紧张', casualties: '9人死亡', impact: '极高'}, {date: '2019-02-14', title: '普尔瓦马袭击', desc: '自杀式炸弹袭击中央后备警察部队车队', casualties: '40人死亡', impact: '极高'}, {date: '2020-02', title: '巴拉科特空袭', desc: '印度越境空袭疑似JeM营地，引发两国局势升级', casualties: '伤亡数字争议', impact: '高'}], statements: [{date: '2019-02', source: 'JeM声明', content: '宣称对普尔瓦马袭击负责，称是对印度在克什米尔政策的报复。'}] },
  { id: 'haqqani', name: '哈卡尼网络', aliases: ['Haqqani Network', '哈卡尼集团'], type: '恐怖组织', category: '宗教极端', subcategory: '普什图圣战网络', founded: '1970s', foundedLocation: '阿富汗帕克蒂亚省/北瓦济里斯坦', status: '活跃', threatLevel: 8.5, threatTrend: '稳定', leader: '西拉杰丁·哈卡尼', formerLeaders: ['贾拉勒丁·哈卡尼（2018死亡）'], members: '数千人', operatingRegions: ['阿富汗', '巴基斯坦'], ideology: '建立伊斯兰酋长国，与塔利班目标一致', funding: '绑架赎金、毒品贸易、外部捐助、塔利班支持', fundingEstimate: '年收入数千万美元', designation: ['联合国安理会制裁', '美国指定外国恐怖组织'], weaponLevel: '轻武器+IED+自杀式炸弹+火箭弹', cyberCapability: '低', description: '哈卡尼网络是阿富汗-巴基斯坦边境地区最具影响力的武装组织之一，与塔利班关系密切但保持半独立运作。以复杂的城市袭击和绑架行动著称，被联合国和美国列为恐怖组织。', structure: [{role: '领导人', current: '西拉杰丁·哈卡尼', desc: '2021年后任阿富汗塔利班政府内政部长'}, {role: '军事指挥官', current: '—', desc: '跨境袭击指挥'}, {role: '资金网络', current: '—', desc: '绑架与走私收益'}], events: [{date: '2008-07-07', title: '喀布尔印度使馆爆炸', desc: '自杀式汽车炸弹袭击印度驻喀布尔使馆', casualties: '58人死亡', impact: '高'}, {date: '2011-09-13', title: '喀布尔美国使馆袭击', desc: '袭击美国使馆及北约总部', casualties: '16人死亡', impact: '高'}, {date: '2018-01-20', title: '洲际酒店袭击', desc: '袭击喀布尔洲际酒店', casualties: '22人死亡', impact: '高'}], statements: [{date: '2021-09', source: '塔利班政府公告', content: '西拉杰丁·哈卡尼出任阿富汗伊斯兰酋长国内政部长。'}] },
  { id: 'isis_k', name: '伊斯兰国呼罗珊省', aliases: ['ISIS-K', 'ISKP', 'ISIS-Khorasan'], type: '恐怖组织', category: '宗教极端', subcategory: '逊尼派萨拉菲圣战', founded: '2015', foundedLocation: '阿富汗/巴基斯坦边境', status: '活跃', threatLevel: 9.0, threatTrend: '上升', leader: '沙拉夫丁·莫塔津（公开信息有限）', formerLeaders: ['哈菲兹·赛义德·汗（2015击毙）'], members: '约1,000-5,000人', operatingRegions: ['阿富汗', '巴基斯坦', '中亚', '伊朗'], ideology: '在呼罗珊地区建立哈里发国，袭击什叶派、西方及塔利班目标', funding: '抢劫、勒索、外部捐助、阿富汗混乱局势中获利', fundingEstimate: '规模中等', designation: ['联合国安理会1267委员会制裁', '美国指定外国恐怖组织', '欧盟指定恐怖组织'], weaponLevel: '轻武器+IED+自杀式炸弹', cyberCapability: '中——利用社交媒体宣传', description: 'ISIS-K是伊斯兰国在阿富汗-巴基斯坦地区的分支，是ISIS最活跃和致命的分支之一。在塔利班重掌阿富汗后，ISIS-K发动多起针对清真寺、机场和外交设施的袭击。', structure: [{role: '省长', current: '沙拉夫丁·莫塔津', desc: '呼罗珊省最高指挥官'}, {role: '军事委员会', current: '—', desc: '袭击策划'}, {role: '宣传部门', content: '—', desc: '媒体与网络宣传'}], events: [{date: '2021-08-26', title: '喀布尔机场爆炸', desc: '在机场外发动自杀式爆炸', casualties: '183人死亡（含13名美军）', impact: '极端'}, {date: '2022-09-30', title: '喀布尔俄罗斯使馆爆炸', desc: '袭击俄罗斯驻喀布尔使馆', casualties: '6人死亡', impact: '高'}, {date: '2024-01-03', title: '伊朗克尔曼爆炸', desc: '在纪念苏莱曼尼集会上发动连环爆炸', casualties: '94人死亡', impact: '极端'}], statements: [{date: '2024-01', source: 'ISIS-K声明', content: '宣称对伊朗克尔曼爆炸负责，称袭击目标是什叶派异教徒。'}] },
  { id: 'lej', name: '先知信徒军', aliases: ['Lashkar-e-Jhangvi', 'LeJ', '羌格维军'], type: '恐怖组织', category: '宗教极端', subcategory: '反什叶派极端组织', founded: '1996', foundedLocation: '巴基斯坦旁遮普省', status: '潜伏活跃', threatLevel: 8.0, threatTrend: '下降', leader: '多名头目已被击毙', formerLeaders: ['里亚兹·巴锡（2002击毙）'], members: '约数百人', operatingRegions: ['巴基斯坦', '阿富汗'], ideology: '消灭什叶派穆斯林，在巴基斯坦建立萨拉菲派政权', funding: '海外捐助、犯罪活动', fundingEstimate: '规模较小', designation: ['联合国安理会制裁', '美国指定外国恐怖组织', '巴基斯坦列禁'], weaponLevel: '轻武器+IED+自杀式炸弹', cyberCapability: '低', description: '先知信徒军是巴基斯坦逊尼派极端组织，以袭击什叶派社区著称，被联合国和美国列为恐怖组织。其残余势力与ISIS-K等组织存在联系。', structure: [{role: '最高指挥官', current: '不详', desc: '多头目已被击毙'}, {role: '行动小组', current: '—', desc: '分散袭击单元'}], events: [{date: '2013-01-10', title: '奎达爆炸', desc: '袭击什叶派聚居区', casualties: '100+人死亡', impact: '极端'}, {date: '2013-02-16', title: '哈扎拉社区爆炸', desc: '针对奎达哈扎拉社区市场炸弹', casualties: '89人死亡', impact: '极端'}], statements: [] },
  { id: 'uwsa', name: '佤邦联合军', aliases: ['UWSA', '佤联军', '缅甸佤邦联合军'], type: '犯罪组织', category: '民族武装', subcategory: '缅甸少数民族武装', founded: '1989', foundedLocation: '缅甸掸邦', status: '活跃', threatLevel: 6.5, threatTrend: '稳定', leader: '鲍有祥', formerLeaders: [], members: '约2万-3万人', operatingRegions: ['缅甸', '泰国', '中国边境'], ideology: '佤族自治，维护佤邦利益', funding: '矿产、赌博、毒品贩运、商业投资', fundingEstimate: '年收入数亿美元', designation: ['缅甸政府视为民族武装组织', '美国财政部制裁部分关联企业'], weaponLevel: '常规武器（含重武器）', cyberCapability: '低', description: '佤邦联合军是缅甸最大的少数民族武装组织之一，控制掸邦北部佤邦地区。其与缅甸政府军保持停火协议，但涉及毒品贩运、网络赌博和矿产走私等问题。', structure: [{role: '总司令', current: '鲍有祥', desc: '最高军事领导人'}, {role: '政治局', current: '—', desc: '行政决策'}, {role: '171军区', current: '—', desc: '泰缅边境部队'}], events: [{date: '1989', title: '脱离缅共成立佤邦', desc: '脱离缅甸共产党，与军政府达成停火', casualties: '—', impact: '高'}, {date: '2015', title: '美国制裁', desc: '美国财政部制裁佤邦相关网络赌博企业', casualties: '—', impact: '中'}], statements: [] },
  { id: 'aa_myanmar', name: '若开军', aliases: ['Arakan Army', 'AA', '阿拉干军'], type: '犯罪组织', category: '民族武装', subcategory: '缅甸少数民族武装', founded: '2009', foundedLocation: '缅甸若开邦', status: '活跃', threatLevel: 7.0, threatTrend: '上升', leader: '通米亚良', formerLeaders: [], members: '约1万-3万人', operatingRegions: ['缅甸若开邦', '钦邦', '孟加拉边境'], ideology: '若开族民族自决，争取若开邦自治', funding: '税收、走私、外国支持', fundingEstimate: '规模中等', designation: ['缅甸政府列为恐怖组织', '美国制裁部分领导人'], weaponLevel: '轻武器+重武器', cyberCapability: '低', description: '若开军是缅甸若开邦主要的民族武装组织，与缅甸政府军长期冲突。近年来军事能力显著增强，控制若开邦大部分地区，对当地中资企业项目和人员安全构成影响。', structure: [{role: '总司令', current: '通米亚良', desc: '最高指挥官'}, {role: '联合若开军政治部门', current: '—', desc: '政治代表'}], events: [{date: '2018-12', title: '若开邦冲突升级', desc: '与缅军在若开邦多地发生激战', casualties: '数百人死亡', impact: '高'}, {date: '2019-01', title: '警方哨所袭击', desc: '袭击若开邦警察哨所', casualties: '13名警察死亡', impact: '高'}, {date: '2023-11', title: '缅北冲突扩大', desc: '与缅军在若开邦及钦邦展开大规模军事行动', casualties: '数千人伤亡', impact: '高'}], statements: [] },
  { id: 'tnla', name: '德昂民族解放军', aliases: ['TNLA', '德昂军', 'Palaung State Liberation Front'], type: '犯罪组织', category: '民族武装', subcategory: '缅甸少数民族武装', founded: '1992', foundedLocation: '缅甸掸邦北部', status: '活跃', threatLevel: 6.5, threatTrend: '上升', leader: '达崩觉', formerLeaders: [], members: '约5,000-8,000人', operatingRegions: ['缅甸掸邦北部'], ideology: '德昂族民族自治', funding: '税收、毒品贸易、玉石走私', fundingEstimate: '规模中等', designation: ['缅甸政府列为恐怖组织'], weaponLevel: '轻武器+地雷', cyberCapability: '低', description: '德昂民族解放军是缅甸掸邦北部德昂族武装组织，参与缅北联盟军事行动。其活动区域涉及中缅边境贸易路线和能源管道周边。', structure: [{role: '主席', current: '达崩觉', desc: '最高领导人'}, {role: '军事委员会', current: '—', desc: '作战指挥'}], events: [{date: '2015', title: '缅北冲突', desc: '与缅军在掸邦北部发生激烈冲突', casualties: '数百人伤亡', impact: '高'}, {date: '2023-10', title: '1027行动', desc: '参与缅北联盟对缅军的大规模进攻', casualties: '数千人伤亡', impact: '高'}], statements: [] },
  { id: 'kia', name: '克钦独立军', aliases: ['KIA', 'Kachin Independence Army'], type: '犯罪组织', category: '民族武装', subcategory: '缅甸少数民族武装', founded: '1961', foundedLocation: '缅甸克钦邦', status: '活跃', threatLevel: 6.5, threatTrend: '稳定', leader: '恩板腊', formerLeaders: [], members: '约8,000-10,000人', operatingRegions: ['缅甸克钦邦', '中缅边境'], ideology: '克钦族民族自决', funding: '玉石贸易、税收、外国支持', fundingEstimate: '规模中等', designation: ['缅甸政府列为非法武装'], weaponLevel: '轻武器+重武器', cyberCapability: '低', description: '克钦独立军是缅甸历史最悠久的民族武装之一，控制克钦邦部分地区。其活动区域与中国在缅北的水电、矿业项目存在交集。', structure: [{role: '总司令', current: '恩板腊', desc: '最高军事指挥官'}, {role: '克钦独立组织', current: '—', desc: '政治翼'}], events: [{date: '1994', title: '停火协议', desc: '与军政府签署17年停火协议', casualties: '—', impact: '高'}, {date: '2011', title: '停火破裂', desc: '与缅军爆发新一轮冲突', casualties: '数千人伤亡', impact: '高'}], statements: [] },
  { id: 'abu_sayyaf', name: '阿布沙耶夫组织', aliases: ['Abu Sayyaf Group', 'ASG', '菲律宾伊斯兰武装'], type: '恐怖组织', category: '宗教极端', subcategory: '分离主义圣战', founded: '1991', foundedLocation: '菲律宾巴西兰岛', status: '潜伏活跃', threatLevel: 7.5, threatTrend: '下降', leader: '拉杜兰·萨希隆（2017死亡）', formerLeaders: ['阿布杜拉贾克·阿布巴卡尔·简加拉尼（1998击毙）'], members: '约300-500人（鼎盛期数千）', operatingRegions: ['菲律宾苏禄群岛', '婆罗洲'], ideology: '在菲律宾南部建立伊斯兰国家，通过绑架勒索筹资', funding: '绑架赎金、走私、外部捐助', fundingEstimate: '年收入数百万美元', designation: ['联合国安理会制裁', '美国指定外国恐怖组织', '菲律宾列禁'], weaponLevel: '轻武器+IED+绑架', cyberCapability: '低', description: '阿布沙耶夫是菲律宾南部极端武装组织，以绑架外国人质和海上绑架著称，与基地组织有历史联系。近年来在菲律宾军方打击下实力大减。', structure: [{role: '领导人', current: '拉杜兰·萨希隆', desc: '2016-2017年领导人'}, {role: '地方指挥官', current: '—', desc: '各岛分散小组'}], events: [{date: '2000-04-23', title: '西帕丹岛绑架', desc: '绑架21名游客包括多名西方人', casualties: '全部获释', impact: '高'}, {date: '2017-05-23', title: '马拉维危机', desc: '与马乌特集团联合占领马拉维市', casualties: '约1,200人死亡', impact: '极高'}, {date: '2017-10-16', title: '萨希隆被击毙', desc: '菲律宾军方击毙其领导人', casualties: '—', impact: '高'}], statements: [] },
  { id: 'maute', name: '马乌特集团', aliases: ['Maute Group', '伊斯兰马乌特'], type: '恐怖组织', category: '宗教极端', subcategory: 'ISIS菲律宾分支', founded: '2012', foundedLocation: '菲律宾棉兰老岛', status: '被重创', threatLevel: 7.0, threatTrend: '下降', leader: '奥马尔·马乌特（2017死亡）', formerLeaders: ['阿卜杜拉·马乌特（2017死亡）'], members: '约200-500人', operatingRegions: ['菲律宾棉兰老岛'], ideology: '在菲律宾建立哈里发国', funding: '毒品贸易、外部捐助、ISIS支持', fundingEstimate: '规模较小', designation: ['菲律宾列禁', '美国指定恐怖组织'], weaponLevel: '轻武器+IED', cyberCapability: '低', description: '马乌特集团是菲律宾棉兰老岛极端武装，2017年与阿布沙耶夫联合占领马拉维市，引发持续五个月的马拉维危机。', structure: [{role: '领导人', current: '奥马尔·马乌特', desc: '创始人之一'}, {role: '马乌特家族', current: '—', desc: '核心领导层'}], events: [{date: '2017-05-23', title: '马拉维占领', desc: '占领棉兰老岛马拉维市', casualties: '约1,200人死亡', impact: '极高'}, {date: '2017-10-23', title: '马拉维解放', desc: '菲军方宣布夺回马拉维', casualties: '—', impact: '高'}], statements: [] },
  { id: 'jemaah_islamiyah', name: '伊斯兰祈祷团', aliases: ['Jemaah Islamiyah', 'JI', '伊斯兰团体'], type: '恐怖组织', category: '宗教极端', subcategory: '东南亚圣战网络', founded: '1993', foundedLocation: '马来西亚/印尼', status: '潜伏活跃', threatLevel: 7.5, threatTrend: '下降', leader: '不详', formerLeaders: ['阿布·巴卡尔·巴希尔（2020死亡）'], members: '约数百人', operatingRegions: ['印度尼西亚', '马来西亚', '菲律宾', '泰国', '澳大利亚'], ideology: '在东南亚建立伊斯兰国家', funding: '海外捐助、犯罪活动、慈善掩护', fundingEstimate: '规模中等', designation: ['联合国安理会制裁', '美国指定外国恐怖组织', '印尼列禁'], weaponLevel: '炸弹+自杀式袭击', cyberCapability: '低', description: '伊斯兰祈祷团是东南亚最具影响力的圣战组织之一，与基地组织有历史联系，策划了2002年巴厘岛爆炸案。近年实力受挫但仍具威胁。', structure: [{role: '精神领袖', current: '阿布·巴卡尔·巴希尔', desc: '创始人'}, {role: '行动小组', current: '—', desc: '分散单元'}], events: [{date: '2002-10-12', title: '巴厘岛爆炸', desc: '夜总会炸弹袭击', casualties: '202人死亡', impact: '极端'}, {date: '2003-08-05', title: '雅加达万豪酒店爆炸', desc: '汽车炸弹袭击酒店', casualties: '12人死亡', impact: '高'}, {date: '2009-07-17', title: '雅加达丽思卡尔顿爆炸', desc: '酒店连环爆炸', casualties: '9人死亡', impact: '高'}], statements: [] },
  { id: 'mit', name: '东印尼圣战者', aliases: ['MIT', 'Eastern Indonesia Mujahideen', '圣战者东印尼'], type: '恐怖组织', category: '宗教极端', subcategory: 'ISIS印尼分支', founded: '2010', foundedLocation: '印度尼西亚中苏拉威西', status: '被重创', threatLevel: 7.0, threatTrend: '下降', leader: '阿里·卡洛拉（2016击毙）', formerLeaders: ['桑托索（2016击毙）'], members: '约数十人', operatingRegions: ['印度尼西亚中苏拉威西'], ideology: '在印尼建立伊斯兰国家，效忠ISIS', funding: '抢劫、绑架、外部捐助', fundingEstimate: '规模较小', designation: ['美国指定外国恐怖组织', '印尼列禁'], weaponLevel: '轻武器+IED', cyberCapability: '低', description: '东印尼圣战者是印尼中苏拉威西的极端武装，曾宣誓效忠ISIS。经过多年军事清剿，其核心成员已被击毙，但残余势力仍在活动。', structure: [{role: '领导人', current: '阿里·卡洛拉', desc: '末任领导人'}, {role: '残余成员', current: '—', desc: '分散潜伏'}], events: [{date: '2014', title: '宣誓效忠ISIS', desc: '宣布效忠巴格达迪', casualties: '—', impact: '高'}, {date: '2016', title: '桑托索被击毙', desc: '印尼安全部队击毙其领导人', casualties: '—', impact: '高'}], statements: [] },
  { id: 'brn', name: '北大年马来民族革命阵线', aliases: ['BRN', 'Barisan Revolusi Nasional', '民族革命阵线'], type: '犯罪组织', category: '民族武装', subcategory: '泰国南部分离武装', founded: '1963', foundedLocation: '泰国北大年', status: '活跃', threatLevel: 6.5, threatTrend: '稳定', leader: '集体领导', formerLeaders: [], members: '约1,000-3,000人', operatingRegions: ['泰国南部三府', '马来西亚边境'], ideology: '马来族独立，建立北大年独立国', funding: '海外捐助、犯罪活动、税收', fundingEstimate: '规模中等', designation: ['泰国列禁'], weaponLevel: '轻武器+IED+伏击', cyberCapability: '低', description: 'BRN是泰国南部最主要的马来族分离武装组织，长期发动针对政府军、学校和平民的袭击。其活动区域靠近马来西亚边境，影响泰国南部稳定。', structure: [{role: '舒拉委员会', current: '集体领导', desc: '决策机构'}, {role: '战斗小组', current: '—', desc: '分散行动单元'}], events: [{date: '2004', title: '塔克拜袭击', desc: '袭击警察局并盗取武器', casualties: '—', impact: '高'}, {date: '2019-11', title: '宋卡府袭击', desc: '伏击安全部队车辆', casualties: '15人死亡', impact: '高'}], statements: [] },
  { id: 'huji_b', name: '孟加拉伊斯兰圣战运动', aliases: ['HUJI-B', 'Harkat-ul-Jihad-al-Islami Bangladesh'], type: '恐怖组织', category: '宗教极端', subcategory: '南亚圣战网络', founded: '1992', foundedLocation: '孟加拉国', status: '潜伏活跃', threatLevel: 7.0, threatTrend: '稳定', leader: '不详', formerLeaders: [], members: '约数百人', operatingRegions: ['孟加拉国', '缅甸', '印度'], ideology: '在孟加拉国建立伊斯兰政权', funding: '海外捐助、犯罪活动', fundingEstimate: '规模较小', designation: ['美国指定外国恐怖组织', '孟加拉国列禁'], weaponLevel: '轻武器+IED', cyberCapability: '低', description: 'HUJI-B是孟加拉国激进组织，与基地组织和虔诚军有联系，被美国和孟加拉国列为恐怖组织。其成员涉及多起针对世俗人士和外国人的袭击。', structure: [{role: '埃米尔', current: '不详', desc: '最高领袖'}, {role: '行动网络', current: '—', desc: '分散单元'}], events: [{date: '2001', title: '暗杀记者', desc: '杀害孟加拉记者', casualties: '1人死亡', impact: '高'}, {date: '2004', title: '谢赫·哈西娜袭击', desc: '暗杀时任反对派领袖未遂', casualties: '20人死亡', impact: '高'}], statements: [] },

  // 中东
  { id: 'hts', name: '沙姆解放组织', aliases: ['HTS', 'Hayat Tahrir al-Sham', '努斯拉阵线', 'Jabhat al-Nusra'], type: '恐怖组织', category: '宗教极端', subcategory: '叙利亚圣战武装', founded: '2012', foundedLocation: '叙利亚', status: '活跃（执政叙利亚过渡政府）', threatLevel: 7.5, threatTrend: '稳定', leader: '艾哈迈德·沙拉', formerLeaders: ['阿布·穆罕默德·朱拉尼'], members: '约1万-2万人', operatingRegions: ['叙利亚', '土耳其', '黎巴嫩'], ideology: '推翻阿萨德政权，在叙利亚建立伊斯兰政权', funding: '税收、走私、外部捐助、土耳其支持', fundingEstimate: '年收入数亿美元', designation: ['联合国安理会制裁', '美国指定外国恐怖组织', '欧盟指定恐怖组织', '土耳其列禁（后关系变化）'], weaponLevel: '轻武器+重武器+IED', cyberCapability: '中', description: 'HTS前身为努斯拉阵线，曾是基地组织叙利亚分支，后与基地组织切割并主导叙利亚反对派。2024年底推翻阿萨德政权后成为叙利亚过渡政府核心力量。', structure: [{role: '领导人', current: '艾哈迈德·沙拉', desc: '叙利亚过渡政府事实领导人'}, {role: '舒拉委员会', current: '—', desc: '决策机构'}, {role: '军事指挥部', current: '—', desc: '作战指挥'}], events: [{date: '2016-07', title: '与基地组织切割', desc: '宣布改名为Jabhat Fateh al-Sham并脱离基地组织', casualties: '—', impact: '高'}, {date: '2017-01', title: '组建HTS', desc: '合并多个反对派武装成立HTS', casualties: '—', impact: '高'}, {date: '2024-12', title: '推翻阿萨德政权', desc: 'HTS主导攻势攻占大马士革', casualties: '数千人伤亡', impact: '极端'}], statements: [] },
  { id: 'ahrar', name: '自由沙姆人伊斯兰运动', aliases: ['Ahrar al-Sham', '黎凡特自由人'], type: '恐怖组织', category: '宗教极端', subcategory: '叙利亚伊斯兰武装', founded: '2011', foundedLocation: '叙利亚伊德利卜', status: '活跃', threatLevel: 6.5, threatTrend: '下降', leader: '贾比尔·阿里·谢赫', formerLeaders: ['哈桑·阿卜杜勒·加尼'], members: '约数千人', operatingRegions: ['叙利亚西北部'], ideology: '在叙利亚建立伊斯兰政府', funding: '土耳其、卡塔尔支持，海外捐助', fundingEstimate: '规模中等', designation: ['美国列为恐怖组织', '俄罗斯列为恐怖组织'], weaponLevel: '轻武器+重武器', cyberCapability: '低', description: '自由沙姆人是叙利亚内战中的重要伊斯兰武装组织，与土耳其关系密切。曾被美国和俄罗斯列为恐怖组织。', structure: [{role: '领导人', current: '贾比尔·阿里·谢赫', desc: '最高指挥官'}, {role: '舒拉委员会', current: '—', desc: '决策机构'}], events: [{date: '2013', title: '成为主要反对派', desc: '在叙利亚西北部扩张势力', casualties: '—', impact: '高'}, {date: '2018', title: '伊德利卜冲突', desc: '与HTS在伊德利卜发生冲突', casualties: '数百人伤亡', impact: '高'}], statements: [] },
  { id: 'asaib', name: '阿萨伊卜·阿赫勒·哈克', aliases: ['Asaib Ahl al-Haq', 'AAH', '正义联盟'], type: '恐怖组织', category: '宗教极端', subcategory: '伊拉克什叶派民兵', founded: '2006', foundedLocation: '伊拉克', status: '活跃', threatLevel: 7.0, threatTrend: '稳定', leader: '卡伊斯·哈扎利', formerLeaders: [], members: '约1万+人', operatingRegions: ['伊拉克', '叙利亚', '黎巴嫩'], ideology: '什叶派伊斯兰主义，反美反以色列，效忠伊朗', funding: '伊朗革命卫队圣城旅、伊拉克政府预算、商业活动', fundingEstimate: '年收入数千万美元', designation: ['美国指定外国恐怖组织', '美国制裁'], weaponLevel: '常规武器+火箭弹+无人机', cyberCapability: '低', description: 'AAH是伊拉克什叶派民兵组织，与伊朗关系密切。曾长期袭击驻伊拉克美军，现为伊拉克人民动员力量（PMF）组成部分，参与政治。', structure: [{role: '秘书长', current: '卡伊斯·哈扎利', desc: '最高领导人'}, {role: '军事委员会', current: '—', desc: '民兵指挥'}, {role: '政治翼', current: '—', desc: '参与伊拉克议会'}], events: [{date: '2007', title: '绑架英国承包商', desc: '杀害5名英国安保人员', casualties: '5人死亡', impact: '高'}, {date: '2019-12', title: '袭击美国使馆', desc: '参与围攻美国驻巴格达使馆', casualties: '—', impact: '高'}], statements: [] },
  { id: 'kataib_hezbollah', name: '真主党旅', aliases: ['Kataib Hezbollah', 'KH', '伊拉克真主党旅'], type: '恐怖组织', category: '宗教极端', subcategory: '伊拉克什叶派民兵', founded: '2003', foundedLocation: '伊拉克', status: '活跃', threatLevel: 7.5, threatTrend: '上升', leader: '艾哈迈德·哈米达维', formerLeaders: ['阿布·马赫迪·穆罕迪斯（2020美军空袭死亡）'], members: '约数千至1万人', operatingRegions: ['伊拉克', '叙利亚'], ideology: '什叶派伊斯兰主义，反美，效忠伊朗', funding: '伊朗革命卫队圣城旅、伊拉克政府预算', fundingEstimate: '年收入数千万美元', designation: ['美国指定外国恐怖组织', '美国制裁', '伊拉克列禁（部分时期）'], weaponLevel: '火箭弹+无人机+常规武器', cyberCapability: '中', description: '真主党旅是伊拉克最强大和激进的什叶派民兵之一，与伊朗革命卫队关系密切。多次袭击驻伊拉克美军和外交设施。', structure: [{role: '领导人', current: '艾哈迈德·哈米达维', desc: '最高指挥官'}, {role: '军事委员会', current: '—', desc: '作战指挥'}], events: [{date: '2020-01-27', title: '美军空袭', desc: '美军空袭打死领导人穆罕迪斯和伊朗将领苏莱曼尼', casualties: '10人死亡', impact: '极高'}, {date: '2023-11', title: '袭击美军基地', desc: '多次用无人机和火箭弹袭击伊拉克美军基地', casualties: '—', impact: '高'}], statements: [] },
  { id: 'aqap', name: '阿拉伯半岛基地组织', aliases: ['AQAP', 'Al-Qaeda in the Arabian Peninsula', '也门基地组织'], type: '恐怖组织', category: '宗教极端', subcategory: '基地组织分支', founded: '2009', foundedLocation: '也门', status: '潜伏活跃', threatLevel: 8.0, threatTrend: '下降', leader: '哈立德·巴塔菲（2021死亡）', formerLeaders: ['安瓦尔·奥拉基（2011美军无人机击毙）', '纳赛尔·乌哈希（2015击毙）'], members: '约数百至数千人', operatingRegions: ['也门', '沙特阿拉伯'], ideology: '推翻沙特和也门政府，对西方发动袭击', funding: '抢劫、税收、绑架、外部捐助', fundingEstimate: '规模中等', designation: ['联合国安理会制裁', '美国指定外国恐怖组织', '沙特列禁'], weaponLevel: '轻武器+IED+爆炸装置', cyberCapability: '中——网络杂志《启发》', description: 'AQAP是基地组织最危险的分支之一，策划了2009年圣诞节炸机未遂和2015年《查理周刊》袭击。在也门内战中曾控制大片领土。', structure: [{role: '埃米尔', current: '哈立德·巴塔菲', desc: '最高领导人'}, {role: '军事委员会', current: '—', desc: '袭击策划'}, {role: '媒体部门', current: '—', desc: '《启发》杂志'}], events: [{date: '2009-12-25', title: '圣诞节炸机未遂', desc: ' Nigerian 青年携带炸弹试图炸毁美国客机', casualties: '未遂', impact: '极高'}, {date: '2015-01-07', title: '查理周刊袭击', desc: 'AQAP宣称对巴黎查理周刊枪击负责', casualties: '12人死亡', impact: '极高'}, {date: '2020-08', title: '美军空袭', desc: '美军无人机空袭打死领导人哈立德·巴塔菲', casualties: '1人', impact: '高'}], statements: [{date: '2010', source: '《启发》杂志', content: '号召在西方发动独狼式袭击，提供制作炸弹指南。'}] },
  { id: 'houthis', name: '胡塞武装', aliases: ['Ansar Allah', '胡塞运动', '也门胡塞'], type: '恐怖组织', category: '宗教极端', subcategory: '什叶派伊斯兰主义武装', founded: '1994', foundedLocation: '也门萨达省', status: '活跃（控制也门首都）', threatLevel: 7.5, threatTrend: '上升', leader: '阿卜杜勒-马利克·胡塞', formerLeaders: ['侯赛因·胡塞（2004死亡）'], members: '约数万至20万人', operatingRegions: ['也门', '沙特阿拉伯', '红海', '曼德海峡'], ideology: '什叶派宰德派政治宗教运动，反美反以色列', funding: '伊朗支持、税收、走私', fundingEstimate: '年收入数亿美元', designation: ['美国指定外国恐怖组织（2024）', '联合国制裁部分领导人', '沙特、阿联酋列禁'], weaponLevel: '导弹+无人机+火箭弹+轻武器', cyberCapability: '中', description: '胡塞武装是也门宰德派反政府武装，2014年占领首都萨那，2015年起与沙特领导的联军作战。2023-2024年频繁使用导弹和无人机袭击红海商船及以色列目标，严重影响国际航运。', structure: [{role: '最高领导人', current: '阿卜杜勒-马利克·胡塞', desc: '最高政治军事领袖'}, {role: '最高革命委员会', current: '—', desc: '政治决策'}, {role: '军事指挥部', current: '—', desc: '导弹与无人机部队'}], events: [{date: '2014-09', title: '占领萨那', desc: '攻占也门首都', casualties: '—', impact: '极高'}, {date: '2015-03', title: '沙特联军介入', desc: '沙特领导多国联军对胡塞发动空袭', casualties: '数万人伤亡', impact: '极高'}, {date: '2023-11', title: '红海袭船', desc: '使用导弹和无人机袭击红海国际商船', casualties: '—', impact: '极高'}, {date: '2024-01', title: '美英空袭', desc: '美英对胡塞目标发动多轮空袭', casualties: '—', impact: '高'}], statements: [{date: '2023-11', source: '胡塞武装声明', content: '宣布封锁红海，打击与以色列有关的船只。'}] },
  { id: 'pij', name: '巴勒斯坦伊斯兰圣战运动', aliases: ['Palestinian Islamic Jihad', 'PIJ', '杰哈德'], type: '恐怖组织', category: '宗教极端', subcategory: '巴勒斯坦伊斯兰武装', founded: '1981', foundedLocation: '埃及加沙', status: '活跃', threatLevel: 7.0, threatTrend: '上升', leader: '齐亚德·纳哈拉', formerLeaders: ['法蒂·什卡基（1995死亡）'], members: '约数千人', operatingRegions: ['加沙地带', '约旦河西岸', '黎巴嫩', '伊朗'], ideology: '消灭以色列，建立伊斯兰巴勒斯坦国', funding: '伊朗支持、叙利亚支持', fundingEstimate: '年收入数千万美元', designation: ['美国指定外国恐怖组织', '欧盟指定恐怖组织', '以色列列禁'], weaponLevel: '火箭弹+轻武器', cyberCapability: '低', description: 'PIJ是仅次于哈马斯的巴勒斯坦伊斯兰武装组织，得到伊朗大量支持。频繁从加沙向以色列发射火箭弹，是以色列-巴勒斯坦冲突中的重要行为体。', structure: [{role: '总书记', current: '齐亚德·纳哈拉', desc: '最高领导人'}, {role: '军事翼圣城旅', current: '—', desc: '军事行动'}], events: [{date: '2022-08', title: '黎明行动', desc: '以色列对PIJ目标发动军事行动', casualties: '49人死亡', impact: '高'}, {date: '2023-10', title: '阿克萨洪水响应', desc: '参与对以色列火箭弹袭击', casualties: '—', impact: '高'}], statements: [] },

  // 非洲
  { id: 'aqim', name: '伊斯兰马格里布基地组织', aliases: ['AQIM', 'Al-Qaeda in the Islamic Maghreb', '马格里布基地组织'], type: '恐怖组织', category: '宗教极端', subcategory: '北非圣战组织', founded: '1998', foundedLocation: '阿尔及利亚', status: '潜伏活跃', threatLevel: 7.5, threatTrend: '下降', leader: '阿卜杜勒-马利克·德鲁克达尔（2020死亡）', formerLeaders: [], members: '约数百至数千人', operatingRegions: ['阿尔及利亚', '马里', '尼日尔', '利比亚', '布基纳法索'], ideology: '在北非建立伊斯兰国家，袭击西方及当地政府', funding: '绑架赎金、走私、税收', fundingEstimate: '年收入数千万美元', designation: ['联合国安理会制裁', '美国指定外国恐怖组织', '欧盟指定恐怖组织'], weaponLevel: '轻武器+IED+绑架', cyberCapability: '低', description: 'AQIM是基地组织在北非的分支，曾在北非和西非发动多起绑架和袭击。其部分成员后来分裂组成JNIM和ISGS。', structure: [{role: '埃米尔', current: '阿卜杜勒-马利克·德鲁克达尔', desc: '长期领导人'}, {role: '撒哈拉分部', current: '—', desc: '萨赫勒地区行动'}], events: [{date: '2008', title: '加入基地组织', desc: '正式宣布效忠基地组织', casualties: '—', impact: '高'}, {date: '2013-01', title: '因阿迈纳斯人质危机', desc: '袭击阿尔及利亚天然气田', casualties: '67人死亡', impact: '极高'}], statements: [] },
  { id: 'jnim', name: '支持伊斯兰与穆斯林群', aliases: ['JNIM', 'Jamaat Nusrat al-Islam wal-Muslimin', '西非圣战联盟'], type: '恐怖组织', category: '宗教极端', subcategory: '萨赫勒圣战联盟', founded: '2017', foundedLocation: '马里', status: '活跃', threatLevel: 8.0, threatTrend: '上升', leader: '伊亚德·阿格·加力', formerLeaders: [], members: '约2,000-5,000人', operatingRegions: ['马里', '布基纳法索', '尼日尔', '科特迪瓦'], ideology: '在萨赫勒地区建立伊斯兰国家', funding: '绑架赎金、抢劫、税收、毒品贸易', fundingEstimate: '年收入数千万美元', designation: ['联合国安理会制裁', '美国指定外国恐怖组织', '欧盟指定恐怖组织'], weaponLevel: '轻武器+IED+伏击+火箭弹', cyberCapability: '低', description: 'JNIM是2017年由多个萨赫勒圣战组织合并而成的联盟，与基地组织结盟。是马里、布基纳法索和尼日尔安全局势恶化的主要推手。', structure: [{role: '埃米尔', current: '伊亚德·阿格·加力', desc: '最高领导人'}, {role: '安萨尔丁', current: '—', desc: '马里分支'}, {role: '穆拉比通', current: '—', desc: '跨国分支'}], events: [{date: '2017-03', title: '宣布成立', desc: '多个组织合并成立JNIM', casualties: '—', impact: '高'}, {date: '2017-06', title: '康加巴袭击', desc: '袭击马里旅游胜地', casualties: '5人死亡', impact: '高'}, {date: '2021-08', title: '马里政变', desc: '利用政治动荡扩大控制区', casualties: '—', impact: '高'}], statements: [] },
  { id: 'isgs', name: '大撒哈拉伊斯兰国', aliases: ['ISGS', 'Islamic State in the Greater Sahara', '伊斯兰国大撒哈拉省'], type: '恐怖组织', category: '宗教极端', subcategory: 'ISIS萨赫勒分支', founded: '2015', foundedLocation: '马里/尼日尔边境', status: '活跃', threatLevel: 8.0, threatTrend: '上升', leader: '阿布·瓦利德·萨赫拉维（2021死亡）', formerLeaders: [], members: '约数百至数千人', operatingRegions: ['马里', '尼日尔', '布基纳法索'], ideology: '在萨赫勒建立哈里发国', funding: '抢劫、绑架、外部捐助', fundingEstimate: '规模中等', designation: ['美国指定外国恐怖组织', '联合国制裁'], weaponLevel: '轻武器+IED+伏击', cyberCapability: '低', description: 'ISGS是伊斯兰国在萨赫勒地区的分支，以伏击军车和绑架人质著称。2017年导致4名美国士兵在尼日尔遇袭死亡。', structure: [{role: '领导人', current: '阿布·瓦利德·萨赫拉维', desc: '创始人'}, {role: '战斗小组', current: '—', desc: '分散行动单元'}], events: [{date: '2017-10-04', title: '尼日尔伏击', desc: '伏击美军和尼日尔部队联合巡逻队', casualties: '4名美军和5名尼日尔士兵死亡', impact: '极高'}, {date: '2020-12', title: '尼日利亚村庄屠杀', desc: '袭击尼日尔村庄', casualties: '约100人死亡', impact: '高'}], statements: [] },
  { id: 'adf', name: '民主同盟军', aliases: ['ADF', 'Allied Democratic Forces', '乌干达民主同盟军'], type: '恐怖组织', category: '宗教极端', subcategory: '中非圣战武装', founded: '1995', foundedLocation: '乌干达西部', status: '活跃', threatLevel: 7.5, threatTrend: '上升', leader: '穆萨·巴拉卡萨', formerLeaders: ['贾米尔·穆库卢'], members: '约1,000-2,000人', operatingRegions: ['刚果（金）东部', '乌干达'], ideology: '建立伊斯兰国家，推翻乌干达政府', funding: '走私、税收、外部捐助', fundingEstimate: '规模中等', designation: ['联合国安理会制裁', '美国指定外国恐怖组织', '乌干达列禁'], weaponLevel: '轻武器+IED+绑架', cyberCapability: '低', description: 'ADF是乌干达叛军，后与ISIS结盟并宣誓效忠。活跃于刚果（金）东部，频繁发动袭击和绑架，造成大量平民伤亡。', structure: [{role: '领导人', current: '穆萨·巴拉卡萨', desc: '最高指挥官'}, {role: '战斗小组', current: '—', desc: '分散单元'}], events: [{date: '2019-04', title: '卡辛迪袭击', desc: '在刚果（金）东部发动袭击', casualties: '约20人死亡', impact: '高'}, {date: '2021-06', title: '联合国车队遇袭', desc: '袭击维和部队车队', casualties: '1名意大利大使死亡', impact: '高'}], statements: [] },
  { id: 'lra', name: '圣主抵抗军', aliases: ['LRA', "Lord's Resistance Army", '上帝抵抗军'], type: '恐怖组织', category: '宗教极端', subcategory: '中非极端武装', founded: '1987', foundedLocation: '乌干达北部', status: '潜伏活跃', threatLevel: 6.5, threatTrend: '下降', leader: '约瑟夫·科尼', formerLeaders: [], members: '约100-500人', operatingRegions: ['中非共和国', '刚果（金）', '南苏丹', '苏丹'], ideology: '以十诫为基础的圣灵运动，建立基于圣经律法的政权', funding: '走私、绑架、抢劫', fundingEstimate: '规模较小', designation: ['美国指定外国恐怖组织', '国际刑事法院通缉'], weaponLevel: '轻武器', cyberCapability: '极低', description: 'LRA是乌干达叛军，以绑架儿童、强迫其成为士兵和性奴而臭名昭著。约瑟夫·科尼被国际刑事法院通缉，但该组织仍在非洲中部活动。', structure: [{role: '领导人', current: '约瑟夫·科尼', desc: '精神领袖与指挥官'}, {role: '高级指挥官', current: '—', desc: '分散小组'}], events: [{date: '2003-2004', title: '阿奇oli地区屠杀', desc: '大规模绑架儿童', casualties: '数万人被绑架', impact: '极端'}, {date: '2005', title: '国际刑事法院通缉', desc: '对科尼等发出逮捕令', casualties: '—', impact: '高'}], statements: [] },
  { id: 'ansaru', name: '安萨尔', aliases: ['Ansaru', 'Ansarul Muslimina Fi Biladis Sudan', '尼日利亚安萨尔'], type: '恐怖组织', category: '宗教极端', subcategory: '博科圣地分裂派系', founded: '2012', foundedLocation: '尼日利亚', status: '潜伏活跃', threatLevel: 7.0, threatTrend: '稳定', leader: '不详', formerLeaders: [], members: '约数百人', operatingRegions: ['尼日利亚', '尼日尔', '喀麦隆'], ideology: '在尼日利亚北部建立伊斯兰国家，与博科圣地目标相似但反对滥杀穆斯林', funding: '绑架赎金、抢劫', fundingEstimate: '规模较小', designation: ['美国指定外国恐怖组织', '英国指定恐怖组织'], weaponLevel: '轻武器+IED+绑架', cyberCapability: '低', description: '安萨尔是2012年从博科圣地分裂出来的组织，以绑架外国工人和袭击外国目标著称。其活动对尼日利亚北部中资企业构成安全威胁。', structure: [{role: '领导人', current: '不详', desc: '多头目'}, {role: '行动小组', current: '—', desc: '分散单元'}], events: [{date: '2013-02', title: '法国家庭绑架', desc: '在喀麦隆绑架法国家庭', casualties: '全部获释', impact: '高'}, {date: '2013-08', title: '印度籍工人绑架', desc: '绑架并杀害多名印度建筑工人', casualties: '多人死亡', impact: '高'}], statements: [] },

  // 拉美
  { id: 'cjng', name: '哈利斯科新一代贩毒集团', aliases: ['CJNG', 'Jalisco New Generation Cartel'], type: '犯罪组织', category: '贩毒集团', subcategory: '墨西哥跨国犯罪组织', founded: '2009', foundedLocation: '墨西哥哈利斯科州', status: '活跃', threatLevel: 8.5, threatTrend: '上升', leader: '内梅西奥·奥塞格拉·塞万提斯（埃尔·门乔）', formerLeaders: [], members: '数万人', operatingRegions: ['墨西哥', '美国', '欧洲', '亚洲'], ideology: '无意识形态——商业利益驱动', funding: '毒品贩运（芬太尼、冰毒、可卡因）、武器走私、洗钱、人口贩卖', fundingEstimate: '年收入数十亿美元', designation: ['美国财政部制裁', '墨西哥政府重点打击目标'], weaponLevel: '先进——自动武器、狙击步枪、无人机、装甲车', cyberCapability: '中——利用社交媒体炫耀暴力', description: 'CJNG是墨西哥增长最快、最暴力的贩毒集团之一，与锡那罗亚集团争夺地盘。大量向美国走私芬太尼，是美国阿片类药物危机的主要推手之一。', structure: [{role: '领导人', current: '埃尔·门乔', desc: '创始人与最高领袖'}, {role: '地方头目', current: '—', desc: '各州负责人'}, {role: '武装分支', current: '—', desc: '准军事力量'}], events: [{date: '2015-05-01', title: '哈利斯科扫毒行动', desc: '墨西哥军方打击CJNG引发大规模暴力', casualties: '数十人死亡', impact: '高'}, {date: '2020', title: '芬太尼危机高峰', desc: '美国芬太尼过量死亡激增', casualties: '数万人死亡', impact: '极端'}, {date: '2022-02', title: '美国悬赏', desc: '美国悬赏1500万美元抓捕埃尔·门乔', casualties: '—', impact: '高'}], statements: [] },
  { id: 'gulf_cartel', name: '海湾贩毒集团', aliases: ['Gulf Cartel', 'Cartel del Golfo', '洛斯梅塔罗斯'], type: '犯罪组织', category: '贩毒集团', subcategory: '墨西哥跨国犯罪组织', founded: '1930s', foundedLocation: '墨西哥塔毛利帕斯州', status: '活跃', threatLevel: 7.5, threatTrend: '稳定', leader: '多头目制', formerLeaders: ['奥西埃尔·卡德纳斯·纪廉', '安东尼奥·卡德纳斯·纪廉'], members: '约1,000-5,000人', operatingRegions: ['墨西哥东北部', '美国南部'], ideology: '无意识形态——商业利益驱动', funding: '毒品贩运、走私、敲诈', fundingEstimate: '年收入数亿美元', designation: ['美国财政部制裁', '墨西哥政府打击目标'], weaponLevel: '自动武器+装甲车', cyberCapability: '低', description: '海湾贩毒集团是墨西哥历史最悠久的贩毒集团之一，曾培养洛斯塞塔斯为其武装翼。控制墨西哥东北部向美国的主要贩运走廊。', structure: [{role: '领导人', current: '多头目', desc: '家族与派系共治'}, {role: '洛斯梅塔罗斯', current: '—', desc: '武装分支'}], events: [{date: '1999-2003', title: '洛斯塞塔斯成立', desc: '招募军方人员组建武装翼', casualties: '—', impact: '高'}, {date: '2010', title: '集团战争', desc: '与洛斯塞塔斯爆发血腥内战', casualties: '数千人死亡', impact: '极端'}], statements: [] },
  { id: 'los_zetas', name: '洛斯塞塔斯', aliases: ['Los Zetas', '塞塔斯', '墨西哥特种部队贩毒集团'], type: '犯罪组织', category: '贩毒集团', subcategory: '墨西哥跨国犯罪组织', founded: '1997', foundedLocation: '墨西哥', status: '分裂衰落', threatLevel: 7.0, threatTrend: '下降', leader: '多头目', formerLeaders: ['阿尔图罗·德古斯曼·戴塞纳（2002死亡）', '米格尔·特雷维尼奥·莫拉莱斯（被捕）'], members: '约数千人（鼎盛期过万）', operatingRegions: ['墨西哥', '美国', '中美洲'], ideology: '无意识形态——暴力控制地盘', funding: '毒品贩运、绑架、勒索、石油盗窃', fundingEstimate: '年收入数亿美元', designation: ['美国财政部制裁', '墨西哥政府打击目标'], weaponLevel: '军用级武器、装甲车、火箭筒', cyberCapability: '低', description: '洛斯塞塔斯由墨西哥军队逃兵组建，曾是墨西哥最残忍的犯罪组织之一。以斩首、屠杀和军事化战术著称，现已分裂衰落。', structure: [{role: '领导人', current: '多头目', desc: '分裂派系'}, {role: '军事化武装', current: '—', desc: '前特种部队人员'}], events: [{date: '2010', title: '圣费尔南多大屠杀', desc: '在塔毛利帕斯杀害72名中美洲移民', casualties: '72人死亡', impact: '极端'}, {date: '2011', title: '卡德雷塔赌场袭击', desc: '焚烧赌场造成52人死亡', casualties: '52人死亡', impact: '极端'}, {date: '2012', title: '领导人被捕', desc: '米格尔·特雷维尼奥被捕', casualties: '—', impact: '高'}], statements: [] },
  { id: 'farc_d', name: '哥伦比亚革命武装力量（前成员）', aliases: ['FARC dissidents', 'FARC Segunda Marquetalia', '哥武残余'], type: '犯罪组织', category: '贩毒集团', subcategory: '哥伦比亚武装组织', founded: '2016', foundedLocation: '哥伦比亚', status: '活跃', threatLevel: 7.0, threatTrend: '上升', leader: '伊万·马尔克斯（2022死亡）/ 卢西奥·里奥斯', formerLeaders: ['伊万·马尔克斯'], members: '约2,000-5,000人', operatingRegions: ['哥伦比亚', '委内瑞拉边境', '厄瓜多尔'], ideology: '马克思主义（名义），实际转向毒品经济', funding: '可卡因生产与贩运、敲诈勒索、非法采矿', fundingEstimate: '年收入数亿美元', designation: ['美国指定外国恐怖组织（部分派系）', '哥伦比亚政府打击目标'], weaponLevel: '轻武器+地雷+爆炸物', cyberCapability: '低', description: 'FARC残余是2016年和平协议后拒绝放下武器的哥武前成员组成的多个武装团体。主要从事可卡因生产和贩运，控制哥伦比亚部分地区。', structure: [{role: '领导人', current: '卢西奥·里奥斯', desc: '第二马尔凯塔利亚领导人'}, {role: '地方派系', current: '—', desc: '分散多个武装团体'}], events: [{date: '2016', title: '和平协议签署', desc: 'FARC与政府签署和平协议，部分成员拒绝遣散', casualties: '—', impact: '高'}, {date: '2021', title: '伊万·马尔克斯复出', desc: '前FARC高级领导人宣布重返武装斗争', casualties: '—', impact: '高'}], statements: [] },
  { id: 'eln', name: '哥伦比亚民族解放军', aliases: ['ELN', 'National Liberation Army', '民族解放军'], type: '犯罪组织', category: '民族武装', subcategory: '哥伦比亚左翼武装', founded: '1964', foundedLocation: '哥伦比亚', status: '活跃', threatLevel: 7.0, threatTrend: '稳定', leader: '安东尼奥·加西亚', formerLeaders: [], members: '约2,000-5,000人', operatingRegions: ['哥伦比亚', '委内瑞拉边境', '厄瓜多尔'], ideology: '马克思主义、解放神学、反帝国主义', funding: '可卡因、敲诈勒索、非法采矿、绑架', fundingEstimate: '年收入数千万美元', designation: ['美国指定外国恐怖组织', '欧盟指定恐怖组织', '哥伦比亚列禁'], weaponLevel: '轻武器+地雷+爆炸物', cyberCapability: '低', description: 'ELN是哥伦比亚现存最大的左翼游击组织，长期与政府冲突。近年来通过控制可卡因路线和委内瑞拉边境走私获利，频繁袭击石油基础设施。', structure: [{role: '中央指挥部', current: '安东尼奥·加西亚', desc: '最高领导人'}, {role: '东方战线', current: '—', desc: '主要作战单位'}], events: [{date: '2019-01-17', title: '波哥大警察学院爆炸', desc: '汽车炸弹袭击警察学院', casualties: '22人死亡', impact: '高'}, {date: '2022', title: '绑架军人', desc: '绑架多名哥伦比亚军人', casualties: '—', impact: '高'}], statements: [] },
  { id: 'agc', name: '海湾氏族', aliases: ['AGC', 'Clan del Golfo', 'Gulf Clan', '自治 gang'], type: '犯罪组织', category: '贩毒集团', subcategory: '哥伦比亚有组织犯罪', founded: '2007', foundedLocation: '哥伦比亚安蒂奥基亚', status: '活跃', threatLevel: 7.5, threatTrend: '稳定', leader: '乔瓦尼·达里奥·阿里亚斯', formerLeaders: ['丹尼尔·伦登·埃雷拉（被捕）', '达里奥·安东尼奥·乌苏加（被捕）'], members: '约1,500-3,000人', operatingRegions: ['哥伦比亚', '巴拿马', '中美洲'], ideology: '无意识形态——商业利益驱动', funding: '可卡因贩运、敲诈勒索、非法采矿', fundingEstimate: '年收入数亿美元', designation: ['美国指定外国恐怖组织', '哥伦比亚政府重点打击目标'], weaponLevel: '轻武器+装甲车', cyberCapability: '低', description: '海湾氏族是哥伦比亚最大的有组织犯罪集团，由前右翼准军事组织演变而来。控制哥伦比亚大部分可卡因出口路线，对政府安全部队和平民发动频繁袭击。', structure: [{role: '领导人', current: '乔瓦尼·阿里亚斯', desc: '现任最高头目'}, {role: '地方头目', current: '—', desc: '各地区负责人'}], events: [{date: '2022-05', title: '最大头目被捕', desc: '哥伦比亚抓获头目达里奥·乌苏加', casualties: '—', impact: '高'}, {date: '2022-07', title: '全国罢工威胁', desc: '该组织威胁杀害不遵守罢工令的人', casualties: '多人死亡', impact: '高'}], statements: [] },
  { id: 'shining_path', name: '光辉道路（残余）', aliases: ['Shining Path', 'Sendero Luminoso', '秘鲁共产党'], type: '犯罪组织', category: '民族武装', subcategory: '秘鲁左翼武装', founded: '1969', foundedLocation: '秘鲁阿亚库乔', status: '潜伏活跃', threatLevel: 6.0, threatTrend: '下降', leader: '阿维马埃尔·古斯曼（2021死亡）', formerLeaders: [], members: '约100-300人', operatingRegions: ['秘鲁阿普里马克-埃内-曼塔罗河谷'], ideology: '毛主义，建立新民主主义人民共和国', funding: '毒品贸易、敲诈勒索', fundingEstimate: '规模较小', designation: ['美国指定外国恐怖组织', '秘鲁列禁'], weaponLevel: '轻武器+地雷', cyberCapability: '极低', description: '光辉道路是秘鲁毛主义武装组织，1980-2000年代造成约7万人死亡。创始人古斯曼1992年被捕，2021年死亡。残余势力仍在秘鲁古柯产区活动。', structure: [{role: '创始人', current: '阿维马埃尔·古斯曼', desc: '已故精神领袖'}, {role: '残余指挥', current: '—', desc: '分散小组'}], events: [{date: '1980', title: '发动武装斗争', desc: '开始针对秘鲁政府的游击战', casualties: '数十年间约7万人死亡', impact: '极端'}, {date: '1992', title: '古斯曼被捕', desc: '秘鲁安全部队抓获领导人', casualties: '—', impact: '极高'}, {date: '2021-09-11', title: '古斯曼死亡', desc: '在狱中死亡', casualties: '—', impact: '高'}], statements: [] },

  // 欧亚/中亚
  { id: 'wagner', name: '瓦格纳集团', aliases: ['Wagner Group', 'PMC Wagner', '瓦格纳私人军事公司'], type: '犯罪组织', category: '私人军事公司', subcategory: '俄罗斯雇佣兵组织', founded: '2014', foundedLocation: '俄罗斯', status: '重组中', threatLevel: 7.5, threatTrend: '稳定', leader: '叶夫根尼·普里戈任（2023死亡）', formerLeaders: ['德米特里·乌特金（2023死亡）'], members: '约数千至数万人', operatingRegions: ['俄罗斯', '乌克兰', '叙利亚', '利比亚', '马里', '中非共和国'], ideology: '服务俄罗斯国家利益（名义），商业军事服务', funding: '俄罗斯国防部合同、矿产、商业活动', fundingEstimate: '年收入数亿美元', designation: ['美国指定跨国犯罪组织', '欧盟制裁', '英国制裁'], weaponLevel: '重武器+坦克+炮兵', cyberCapability: '中', description: '瓦格纳集团是俄罗斯私人军事公司，在乌克兰、叙利亚、非洲等多地活动。2023年创始人普里戈任发动兵变后坠机身亡，组织随后被俄罗斯收编重组。', structure: [{role: '创始人', current: '叶夫根尼·普里戈任', desc: '已故'}, {role: '军事指挥官', current: '—', desc: '分散指挥'}, {role: '非洲分支', current: '—', desc: '在马里、中非等地活动'}], events: [{date: '2014', title: '克里米亚行动', desc: '参与俄罗斯吞并克里米亚', casualties: '—', impact: '高'}, {date: '2022-2023', title: '巴赫穆特战役', desc: '参与俄乌冲突巴赫穆特攻防战', casualties: '数万人伤亡', impact: '极高'}, {date: '2023-06-23', title: '瓦格纳兵变', desc: '向莫斯科进军后达成协议', casualties: '—', impact: '极高'}, {date: '2023-08-23', title: '普里戈任坠机身亡', desc: '领导人普里戈任在坠机中死亡', casualties: '10人死亡', impact: '高'}], statements: [{date: '2023-06-23', source: '普里戈任声明', content: '指责俄罗斯国防部对瓦格纳营地发动导弹袭击，宣布向莫斯科进军。'}] },
  { id: 'imu', name: '乌兹别克斯坦伊斯兰运动', aliases: ['IMU', 'Islamic Movement of Uzbekistan', '乌伊运'], type: '恐怖组织', category: '宗教极端', subcategory: '中亚圣战组织', founded: '1991', foundedLocation: '乌兹别克斯坦/塔吉克斯坦', status: '被重创', threatLevel: 6.5, threatTrend: '下降', leader: '乌斯曼·加齐（2015死亡）', formerLeaders: ['塔希尔·尤尔达舍夫（2009死亡）', '朱马·纳曼加尼（2001死亡）'], members: '约数百人', operatingRegions: ['阿富汗', '巴基斯坦', '中亚'], ideology: '在中亚建立伊斯兰国家', funding: '毒品贸易、绑架、外部捐助', fundingEstimate: '规模较小', designation: ['联合国安理会制裁', '美国指定外国恐怖组织', '乌兹别克斯坦列禁'], weaponLevel: '轻武器+IED', cyberCapability: '低', description: 'IMU是1991年成立的中亚圣战组织，曾与塔利班和基地组织结盟。多数领导人在阿富汗-巴基斯坦边境被美军和巴军击毙，组织已严重削弱。', structure: [{role: '埃米尔', current: '乌斯曼·加齐', desc: '末任领导人'}, {role: '军事指挥官', current: '—', desc: '残余势力'}], events: [{date: '1999', title: '吉尔吉斯斯坦袭击', desc: '袭击吉尔吉斯斯坦南部', casualties: '—', impact: '高'}, {date: '2001', title: '朱马·纳曼加尼死亡', desc: '在阿富汗军事行动中被打死', casualties: '—', impact: '高'}, {date: '2014', title: '宣布效忠ISIS', desc: '部分成员宣誓效忠伊斯兰国', casualties: '—', impact: '高'}], statements: [] },
  { id: 'etlo', name: '东突厥斯坦解放组织', aliases: ['ETLO', 'East Turkestan Liberation Organization', '东突解放组织'], type: '恐怖组织', category: '民族分离', subcategory: '新疆分裂武装', founded: '1996', foundedLocation: '土耳其', status: '潜伏', threatLevel: 6.0, threatTrend: '稳定', leader: '不详', formerLeaders: [], members: '规模不详', operatingRegions: ['土耳其', '德国', '中亚'], ideology: '新疆独立，使用暴力手段', funding: '海外捐助、犯罪活动', fundingEstimate: '规模较小', designation: ['中国公安部认定恐怖组织', '联合国相关制裁'], weaponLevel: '轻武器', cyberCapability: '低', description: '东突厥斯坦解放组织是被中国公安部认定的恐怖组织之一，以新疆独立为目标，曾在境外策划针对中国驻外机构的袭击。', structure: [{role: '领导人', current: '不详', desc: '分散领导'}, {role: '海外网络', current: '—', desc: '欧洲与中亚活动'}], events: [{date: '1998', title: '伊斯坦布尔袭击图谋', desc: '涉嫌策划针对中国驻土耳其机构袭击', casualties: '—', impact: '中'}], statements: [] }
];

// 合并去重（按 id）
const byId = new Map();
for (const o of existing) byId.set(o.id, o);
for (const o of fromTemp) byId.set(o.id, o);
for (const o of additional) byId.set(o.id, o);
const merged = Array.from(byId.values());

// 保持原文件的其他代码不变，只替换 THREAT_DATA 定义
const before = content.slice(0, match.index);
const afterStart = match.index + match[0].length;
const after = content.slice(afterStart);
const newContent = before + 'const THREAT_DATA={organizations:' + JSON.stringify(merged) + '};' + after;

fs.writeFileSync(OUT, newContent, 'utf8');
console.log('威胁组织数据库已更新：');
console.log('  原有：' + existing.length);
console.log('  来自 temp：' + fromTemp.length);
console.log('  新增：' + additional.length);
console.log('  去重后总数：' + merged.length);
