const gm = require('./globalmedia');
const scrapers = require('./scrapers');
const t = 'The Many Lives of Chaoshan';
const gate = scrapers.chinaOverseasGate(t);
console.log('gate:', gate);
console.log('focusGate:', gm.chinaFocusGate(t, gate));
console.log('strong:', /中资|中企|华人|华侨|侨胞|使馆|领事馆|领事|撤侨|一带一路|海外项目|境外投资|外派|援外|Chinese company|Chinese embassy|Chinese consulate|Belt and Road|overseas Chinese|Chinese workers|Chinese nationals/i.test(t));
console.log('passRe:', /\b(海外|境外|国外|外交|外事|使馆|领事馆|领事|撤侨|援外|外派|中资|中企|中方人员|中国公民|中国留学生|中国劳工|一带一路|BRI|Belt and Road|中巴经济走廊|中老铁路|雅万高铁|中欧班列|蒙内铁路|亚吉铁路|坦赞铁路|瓜达尔|皎漂|汉班托塔|比雷埃夫斯|钱凯|科伦坡港口城|中白工业园|中俄东线|北极LNG|制裁|关税|贸易战|出口管制|贸易壁垒|技术封锁|反倾销|反补贴|经济胁迫|脱钩|遏制|围堵|冲突|战争|政变|恐袭|袭击|绑架|爆炸|骚乱|抗议|示威|罢工|紧张|安全|风险|威胁|间谍|渗透|监听|网络攻击|黑客|军事|军舰|战机|导弹|无人机|南海|台湾海峡|霍尔木兹|马六甲|苏伊士|红海|关键矿产|稀土|锂|钴|铜|石油|天然气|能源安全|供应链)\b|\b(overseas|abroad|diplomat|embassy|consulate|consular|evacuation|Belt and Road|BRI|CPEC|sanction|tariff|trade war|export control|tech blockade|anti-dumping|countervailing|coercion|decouple|containment|conflict|war|coup|terror|attack|kidnap|blast|riot|protest|strike|tension|security|risk|threat|spy|espionage|surveillance|cyberattack|hack|military|warship|warplane|missile|drone|South China Sea|Taiwan Strait|Hormuz|Malacca|Suez|Red Sea|rare earth|lithium|cobalt|copper|oil|gas|energy security|supply chain)\b/i.test(t));
const countries = gm.GLOBAL_COUNTRIES.filter(c => !/^(中国|中国香港|中国台湾|中国澳门|China|Chinese|Hong Kong|Taiwan|Macau)$/i.test(c.cn)).map(c => c.cn);
console.log('foreignCountry?', new RegExp(countries.map(s => s.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')).join('|'), 'i').test(t));
