plugins {
    id 'com.android.application'
}

android {
    namespace 'com.swupl.orps'
    compileSdk 34

    defaultConfig {
        applicationId "com.swupl.orps"
        minSdk 24
        targetSdk 34
        versionCode 1
        versionName "1.0"
    }
    buildTypes {
        release {
            minifyEnabled false
        }
        debug {
            applicationIdSuffix ""
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}
